### PR TITLE
return all rows even when no grouping is taking place

### PR DESCRIPTION
**Pull request by snopoke**
This will require a major version bump since it's not backwards compatible

Currently the result formatter assumes that if there is no `group_by` that the query will only return a single result. This has lead to workarounds like adding a unique field to `group_by` so that it returns all rows.

This change will instead return all rows from the query keyed by an incrementing row index.

### CODE REVIEW

**Comment by emord** [comment]
how hard will it be to change all of HQ's usages to accommodate this change?

**Comment by snopoke** [comment]
I don't think it will be too hard but won't know for sure until I start working on it. I set up a soft assert to see all the places this would impact and there aren't many.

**Comment by snopoke** [comment]
Just updating here that I still think this is a good change but have not been able to prioritise working on the HQ side.

**Comment by mkangia** [comment]
@snopoke just checking on this, do you plan to work on releasing this sometime soon?

**Comment by mkangia** [comment]
Why do we need HQ changes?

from 
```
Currently the result formatter assumes that if there is no group_by that the query
will only return a single result. This has lead to workarounds like adding a unique 
field to group_by so that it returns all rows.
```
Looked like `sqlagg` isn't used without the group by clause because it won't work without it, and the PR changes only cases where no group_by is specified, so i don't understand why there is a need for HQ change.

@snopoke @kaapstorm

**Comment by snopoke** [comment]
@mkangia I'd have to dig into this again but if it is never used without a group by then maybe we don't need to change HQ code immediately.

**Comment by snopoke** [comment]
@mkangia I'd have to dig into this again but if it is never used without a group by then maybe we don't need to change HQ code immediately.

**Comment by mkangia** [comment]
Thanks @snopoke,
My understanding is that even if it was used without a group by, it was giving incorrect results anyway. So now it would be correct.

Do you plan to release this some time soon now?

**Comment by snopoke** [comment]
I don't have any plans to release it immediately. It's not on my current
list of priority items.

**Comment by mkangia** [comment]
offlined with @snopoke and releasing a beta version with this

Mainly because i am not able to test changes in https://github.com/dimagi/commcare-hq/pull/27020 which updates to use a commit hash but its not getting pulled correctly on travis.

**Pull request merged**
