### PR TITLE
make compatible between python 2 and 3

### PR DESCRIPTION
**Pull request by nickpell**
@emord @millerdev cc: @snopoke

### CODE REVIEW

**Comment by snopoke** [comment]
should add python3 to the travis build matrix as well

**Comment by millerdev** [comment]
Looks like there's more conversion to do to make the tests run on Python 3
https://api.travis-ci.org/jobs/201636887/log.txt

**Comment by emord** [comment]
@nickpell I think you have to update the dependency in setup.py https://github.com/dimagi/sql-agg/blob/master/setup.py#L19

**Comment by nickpell** [comment]
going to close this PR and handle the changes in a series of smaller PRs

**Pull request closed without merging**
