### PR TITLE
tests are currently failing

### PR DESCRIPTION
**Pull request by nickpell**
see whether or not tests are currently failing (they are)

### CODE REVIEW

**Comment by nickpell** [comment]
travis builds are currently failing on master
https://travis-ci.org/dimagi/sql-agg/jobs/107854612

@snopoke @czue @NoahCarnahan

**Comment by czue** [comment]
Here's the relevant output. seems like it's failing to install `unittest2`? maybe we could try pinning it?

```

Installed /tmp/easy_install-lpCL2w/unittest2-1.1.0/.eggs/traceback2-1.4.0-py2.6.egg
Searching for linecache2
Reading https://pypi.python.org/simple/linecache2/
Best match: linecache2 1.0.0
Downloading https://pypi.python.org/packages/source/l/linecache2/linecache2-1.0.0.tar.gz#md5=7b25d0289ec36bff1f9e63c4329ce65c
Processing linecache2-1.0.0.tar.gz
Writing /tmp/easy_install-lpCL2w/unittest2-1.1.0/temp/easy_install-GEYATs/linecache2-1.0.0/setup.cfg
Running linecache2-1.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-lpCL2w/unittest2-1.1.0/temp/easy_install-GEYATs/linecache2-1.0.0/egg-dist-tmp-SOMu90
ERROR:root:Error parsing
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pbr/core.py", line 109, in pbr
    attrs = util.cfg_to_args(path)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pbr/util.py", line 245, in cfg_to_args
    kwargs = setup_cfg_to_setup_kwargs(config)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/pbr/util.py", line 379, in setup_cfg_to_setup_kwargs
    cmd = cls(dist)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/__init__.py", line 124, in __init__
    _Command.__init__(self,dist)
  File "/opt/python/2.6.9/lib/python2.6/distutils/cmd.py", line 62, in __init__
    raise TypeError, "dist must be a Distribution instance"
TypeError: dist must be a Distribution instance
Coverage.py warning: No data was collected.
error: Setup script exited with error in setup command: Error parsing /tmp/easy_install-lpCL2w/unittest2-1.1.0/temp/easy_install-GEYATs/linecache2-1.0.0/setup.cfg: TypeError: dist must be a Distribution instance
```

**Comment by snopoke** [comment]
Ahhh, super irritating!

**Comment by snopoke** [comment]
:white_check_mark:

**Pull request merged**
