### PR TITLE
Add support for views

### PR DESCRIPTION
**Pull request by lwyszomi**
@snopoke 

Allow to build queries on the views.

### CODE REVIEW

**Comment by snopoke** [comment]
Would it be possible to add a test for this?

**Comment by lwyszomi** [comment]
@snopoke Added test which get data from a simple view (view is a user_table copy).

**Comment by lwyszomi** [comment]
@snopoke When this will be released?

**Comment by snopoke** [comment]
It should be released to prod today.

**Comment by lwyszomi** [comment]
@snopoke Thanks, So I will can change to the new version in commcare tomorrow?

**Comment by snopoke** [comment]
You should be able to. You can be 100% sure if you look at the tags which the merge commit is in to see if it's been tagged in any release: https://github.com/dimagi/sql-agg/commit/076f26a1d125b638919dbbf586de574d6ebfbce2

**Comment by lwyszomi** [comment]
@snopoke Hey, Could you release sqlagg to the pip? Or I should use in Commcare requirements github url?

**Comment by snopoke** [comment]
released 0.8.0 to pypi - you can update the HQ requirements

**Comment by lwyszomi** [comment]
@snopoke Thanks

**Pull request merged**
